[env:t-can485]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM8
monitor_port = COM8

build_flags =
  -DCORE_DEBUG_LEVEL=3
  -DARDUINO_USB_CDC_ON_BOOT=0

lib_deps =
  bblanchon/ArduinoJson@^7.2.0
  adafruit/Adafruit NeoPixel@^1.12.3
